### ISSUE TITLE
Support for Persistent Volumes

### ISSUE THREAD

**Issue by mmaier2** [mattf/openshift-spark#2]
Hi,
many thanks for the images. If we would like to have persistence.
Where would be the location to mount persistent volumes (claims) into?

Thanks
Markus

**Comment by mattf** [comment]
you can add persistent volume claims to the master and worker specs in the template. that will give you file:// access. however, you will need to make sure it's consistent across your master, workers and driver. i suggest you use storage that doesn't rely on mounting into the containers, such as an object store.

fyi, i'm going to be tracking https://github.com/redhatanalytics/openshift-spark more closely than this repository in the future.
